"""empty message

Revision ID: 478de527659b
Revises: ee59377b8841
Create Date: 2022-01-14 12:52:36.405482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478de527659b'
down_revision = 'ee59377b8841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
