"""empty message

Revision ID: ee59377b8841
Revises: 10b5a88f8bb4
Create Date: 2022-01-14 11:02:13.461424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee59377b8841'
down_revision = '10b5a88f8bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('whatsappno', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['whatsappno'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'whatsappno')
    # ### end Alembic commands ###
